EXP_NAME: base
SEED: 42

WANDB:
    project: lightning-template
    entity: youngerous 

DATASET:
    name: imdb

GPU:
    accelerator: gpu # set "cpu" for debugging
    strategy: ddp # [null, ddp, dp, ...]
    devices: -1

MODEL:
    pretrained: bert-base-uncased
    load_ckpt_pth: null # src/checkpoints/base-ep3/ckpt-epoch=000-val_loss=0.17290.ckpt
    CHECKPOINT:
        dirpath: src/checkpoints/
        filename: ckpt-{epoch:03d}-{val_loss:.5f}
        save_top_k: 2
        monitor: val_loss
 
MODE:
    do_train_only: False
    do_test_only: False 

TRAIN:
    epoch: 3
    batch_size: 16
    lr: 5e-5
    num_workers: 4
    backend: native
    precision: 32 
    max_steps: -1 # default: disabled
    gradient_clip_val: 0.0 # default: not cliping
    accumulate_grad_batches: 1
    warmup_ratio: 0.1

VALIDATION:
    interval: 1
    earlystop_patience: 3

LOG:
    interval: 50
